export let vids: any[] = [
    {
    id: 1,
    link: "ruFbjKG9LTk",
    alias: "crear-cliente-1",
    nombre: "crear un cliente nuevo, método 1",
    descripcion: "El proceso de crear un cliente nuevo método 1, es realizar una venta desde cero, ingresando correctamente los datos del cliente y del  crédito",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "nuevo 1,crear cliente 1,registrar 1,cliente nuevo 1,nueva venta 1,registrar,cliente nuevo,registrarse cliente 1, registro 1"
    
    },
    {      
    id: 2,
    link: "H_B7pOcfKd8",
    alias: "crear-cliente-2",
    nombre: "crear un cliente nuevo, método 2",
    descripcion: "El proceso de crear un cliente nuevo método 2, es realizar una venta desde cero, ingresando los datos del cliente como del crédito de forma sencilla",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "nuevo 2, crear cliente 2, registrar 2, cliente nuevo 2, nueva venta 2, registrar, cliente nuevo, registrar cliente 2, registro 2"
    },
    {        
    id: 3,
    link: "kGX10LFrlOw",
    alias: "ingresar-abono-crédito-método 1",
    nombre: "ingresar abono a un crédito, método 1",
    descripcion: "El proceso de ingresar abono a un crédito método 1, es registrar en el sistema el abono del cliente, bien sea que la cuota fuera diaria, semanal, quincenal o mensual",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "nuevo abono, ingresar abono, abonar crédito 1, abonar 1, ingresar abono 1, ingresar 1, crédito 1, abonar crédito, como ingresar un abono a un crédito método 1, crédito, como ingresar abono a un crédito método 1"
    },
    {        
    id: 4,
    link: "Cl0ADqnrYsk",
    alias: "ingresar-abono-crédito-método 2-abonar-súper-usuario",
    nombre: "ingresar abono a un crédito, método 2 más abonar como súper usuario",
    descripcion: "El proceso de ingresar abono a un crédito método 2, más abonar como súper usuario es registrar el pago del abono en el sistema, si va abonar como super usuario debe ingresar la súper clave, en este proceso debe cambiar la fecha del abono por el día anterior ya que el sistema no permite ingresar dos veces un abono el mismo día",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "ingresar abono, crédito 2, método 2, abonar súper usuario, ingresar 2, abonar 2, crédito 2, abonar, ingresar abono, credito 2"
    },
    {        
    id: 5,
    link: "VCcwRR9AH5M",
    alias: "aplazar-crédito-lista de recaudo-método 1",
    nombre: "aplazar un crédito desde la lista de recaudo método 1",
    descripcion: "El proceso de aplazar un crédito desde la lista de recaudo, es atrasar  el pago del crédito por un mes a partir de la fecha actual",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "aplazar 1, aplazar crédito 1, lista de recaudo 1, recaudo 1, aplazar crédito método 1, cómo aplazar crédito, aplazar un crédito, aplazar credito 1, como aplazar credito, credito 1"
    },
    {        
    id: 6,
    link: "IcxEu93zfM4",
    alias: "aplazar-crédito-lista de recaudo-método 2",
    nombre: "aplazar un crédito desde la lista de recaudo método 2",
    descripcion: "El proceso de aplazar un crédito desde la lista de recaudo método 2,es postergar el pago del crédito solo por un mes , ya que es el máximo plazo que permite registrar el sistema",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "aplazar crédito 2, aplazar 2, método 2, lista de recaudo 2, crédito 2, aplazar crédito, aplazar un crédito, como aplazar un crédito,crédito 2, aplazar crédito 2, aplazar crédito, como aplazar un crédito, aplazar un crédito desde la ruta de recaudo 2,cómo aplazar un crédito desde la ruta de recaudo 2 "
    },
    {        
    id: 7,
    link: "rvUhpyqhTps",
    alias: "agregar-crédito-lista de recaudo-día",
    nombre: "agregar un crédito a la lista de recaudo del día",
    descripcion: "El proceso de agregar un crédito a la lista de recaudo, es añadir el crédito del  cliente a la ruta de cobro bien sea, diaria, semanal, quincenal o mensual",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "agregar crédito, recaudo del día, agregar crédito a lista, añadir crédito a lista, añadir crédito a la lista de recaudo, agregar un crédito a la lista de recaudo del dia, agregar crédito, añadir crédito a la lista"
    },
    {        
    id: 8,
    link: "MZSVJ0g_3lw",
    alias: "agregar-quitar-gasto en el balance",
    nombre: "agregar,quitar gasto en el balance",
    descripcion: "Esta opción de agregar, quitar gasto en el balance, le permite llevar un registro de todos los desembolsos que se registran en la ruta",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "agregar gasto, quitar un gasto, registrar un gasto, ingresar una inversión, eliminar un gasto,eliminar una inversión, registrar un gasto, registrar una inversión, agregar una salida, registrar una entrada, registrar una inversión"
    },
    {        
    id: 9,
    link: "QQ0LXoylIGI",
    alias: "cambiar-cliente- posición en la ruta",
    nombre: "cambiar un cliente de posición en la ruta",
    descripcion: "El proceso de cambiar un cliente de posición en la ruta, es ubicar el crédito en el lugar de su preferencia, puede ser en los primeros lugares, en la mitad o en el último lugar ",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cambiar cliente, cambiar posición, nueva posición, cambiar cliente de lugar,cambiar cliente de posición en la ruta,elegir nueva posición, posicionar cliente,cambiar cliente de posición"
    },
    {        
    id: 10,
    link: "a-iWLBh6CqA",
    alias: "iniciar-sesión",
    nombre: "cómo iniciar sesión",
    descripcion: "El proceso de iniciar sesión, es ingresar correctamente los datos de acceso a la cuenta",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo inicio sesión, iniciar sesión, inicio, inicio de sesión, como iniciar sesion, iniciar sesión, inicio de sesión"
    },
    {        
    id: 11,
    link: "fiIaD1ylZcg",
    alias: "borrar-abono",
    nombre: "como borrar un abono",
    descripcion: "El proceso de como borrar un abono, es eliminar definitivamente un registro del sistema , en este proceso debe ingresar la super clave para borrar el abono en el crédito",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo borrar abono, borrar un abono, eliminar un abono, quitar un abono, quitar un abono del crédito, quitar un abono"
    },
    {        
    id: 12,
    link: "HzmkGV_C3nA",
    alias: "cambiar-idapp",
    nombre: "como cambiar el idapp",
    descripcion: "El proceso de cambiar el idapp, es modificar el ID único de la aplicación la cual está manejando, para realizar este procedimiento debe ingresar el nuevo idapp y la súper clave en los campos correspondientes",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cambio de idapp, cambiar idapp, como cambiar el idapp, modificar el idapp, modificar idapp, idapp"
    },
    {        
    id: 13,
    link: "v-ufBfiuM6Y",
    alias: "eliminar-crédito",
    nombre: "como eliminar un crédito",
    descripcion: "Esta opción le permite eliminar del sistema toda la información del crédito mas no elimina  los datos del cliente, estos siguen registrados en el sistema, para  realizar este procedimiento debe ingresar la súper clave",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo eliminar un crédito, borrar crédito, eliminar crédito, quitar crédito, eliminar del sistema un crédito, borrar crédito"
    },
    {        
    id: 14,
    link: "2BemC92DK7o",
    alias: "función-balance",
    nombre: "cómo funciona el balance",
    descripcion: "Este procedimiento le permite tener un registro detallado y concreto de todas las entradas y gastos registrados en el sistema, en esta opción  puede seleccionar la fecha en la cual necesita ver el balance",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo funciona el balance, función del balance, información del balance, descripcion del balance, balance"
    },
    {        
    id: 15,
    link: "6aodoTK2YaY",
    alias: "recuperar-cuenta",
    nombre: "cómo recuperar cuenta",
    descripcion: "Este proceso le permite rescatar toda la información de la cuenta, la cual está activa en la nube, para este proceso solo debe ingresar el idapp y el serial de la cuenta a recuperar",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "como recuperar cuenta, recuperar cuenta, recuperación de cuenta, cuenta, recuperar, cuenta a recuperar, proceso de recuperación de cuenta"
    },
    {        
    id: 16,
    link: "X6EjNQbgFJE",
    alias: "sincronizar-caja-desde el balance",
    nombre: "cómo sincronizar la caja desde el balance",
    descripcion: "El proceso de sincronizar la caja desde el balance, le permite mantener actualizada toda la  información de su cuenta en la nube",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo sincronizar caja, actualizar caja, sincronizar la caja desde el balance, actualizar caja desde el balance, sincronizar caja, caja, sincronizar, balance"
    },
    {        
    id: 17,
    link: "cn8mZwFdLGI",
    alias: "copia-local",
    nombre: "copia local",
    descripcion: "El proceso de copia local, le permite recuperar los datos que están almacenados de la cuenta en la nube, este procedimiento lo puede realizar ingresando el idapp y el seria de la cuenta a recuperar",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "copia local, copia, recuperar copia, recuperación de datos, recuperar copia local desde la nube, recuperar datos, copia, local"
    },
    {        
    id: 18,
    link: "A0Y-DJ782dM",
    alias: "descargar-caja-base",
    nombre: "descargar caja base",
    descripcion: "El proceso de descargar caja base, le permite subir los datos a la nube y cerrar la caja del día",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "como descargar caja base, caja base, descargar caja, descargar caja base, como puedo descargar caja base, caja, caja base, descargar"
    },
    {        
    id: 19,
    link: "ZoutXY2zkII",
    alias: "enrutar-crédito",
    nombre: "enrutar un crédito",
    descripcion: "El proceso de enrutar un crédito le permite añadir y posicionar el cliente a  la lista general de recaudo",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo enrutar un crédito, enrutar crédito, enrutar, enrutar un crédito"
    },
    {        
    id: 20,
    link: "Qx4Kuc9InbQ",
    alias: "hacer-descuento-crédito",
    nombre: "hacer un descuento a un crédito",
    descripcion: "El proceso de hacer un descuento a un crédito, es un beneficio que puede aplicar la persona encargada de la ruta en algunos clientes, bien sea por su pago constante o por realizar la cancelación total del crédito ",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo hacer un descuento a un crédito, descuento a un crédito, realizar descuento a un crédito, descontarle a un crédito, rebaja a un crédito, hacer una rebaja a un crédito"
    },
    {        
    id: 21,
    link: "bkhDxKkNSiM",
    alias: "hacer-multa-crédito",
    nombre: "hacer una multa a un crédito",
    descripcion: "El proceso de hacer una multa a un crédito, es penalizar al cliente realizando un aumento al crédito en los intereses, este proceso lo aplica el encargado de la ruta en algunos clientes, si fuera el caso, bien sea por la  demora al momento de terminar de cancelar el  crédito",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo hacer una multa a un crédito, multar a un crédito, realizar una multa a un crédito, multar a un crédito, multa a un crédito, multar un crédito"
    },
    {        
    id: 22,
    link: "_DRdP2qbMMY",
    alias: "limpiar-ruta",
    nombre: "limpiar ruta",
    descripcion: "El proceso de limpiar ruta, es quitar todas las posiciones del sistema que no se está utilizando, pero sin borrar los datos antiguos, realizando este proceso mejora el rendimiento del sistema",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo limpiar ruta, limpiar ruta, limpiar, quitar posiciones del sistema"
    },
    {        
    id: 23,
    link: "xcZp4cpfk6w",
    alias: "modificar-datos-acceso",
    nombre: "modificar datos de acceso",
    descripcion: "El proceso de modificar datos de acceso le permite personalizar los datos de usuario y contraseña, tenga en cuenta que el sistema no permite ingresar caracteres especiales, tildes o espacios en los campos de usuario y contraseña",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo modificar los datos de acceso, modificar datos de acceso, datos de acceso, cambiar datos de acceso, modificar datos"
    },
    {        
    id: 24,
    link: "OMRYDYDCfO8",
    alias: "modificar-crédito",
    nombre: "modificar un crédito",
    descripcion: "El proceso de modificar un crédito, es corregir los datos ingresados al momento de haber creado un crédito en el sistema, tenga en cuenta que si el crédito no tiene ningún tipo de abonos lo puede modificar todo, ingresando la super clave, pero si es lo contrario y el crédito tiene abonos solo puede modificar el plazo del crédito",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo modificar los datos de un crédito, modificar crédito, cambiar los datos de un crédito, modificar un crédito"
    },
    {        
    id: 25,
    link: "eKmLcPP4NFw",
    alias: "realizar-mantenimiento-optimización",
    nombre: "realizar mantenimiento de optimización",
    descripcion: "El proceso de realizar mantenimiento y optimización,le permite limpiar la base de datos antiguos de la aplicación y le ayuda acelera su funcionamiento",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "realizar mantenimiento y optimización, mantenimiento y optimización,mantenimiento y optimización de una ruta, como realizar mantenimiento de optimización, como hacer mantenimiento y optimización de una ruta"
    },
    {        
    id: 26,
    link: "fSknkkejAdw",
    alias: "renovar-crédito-cancelado",
    nombre: "renovar un crédito cancelado",
    descripcion: "El proceso de renovar un crédito cancelado, es reanudarlo nuevamente, en este procedimiento sólo tiene que ingresar los datos del crédito ya que la información del cliente queda guardada en el sistema",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "renovar crédito cancelado,como renovar un crédito cancelado,renovar crédito,reanudar un crédito cancelado,reanudar un crédito,renovar crédito cancelado,como renovar un crédito cancelado,renovar crédito"
    },
    {        
    id: 27,
    link: "7FOAWx-y0VM",
    alias: "resetear-base-datos",
    nombre: "resetear base de datos",
    descripcion: "El proceso de resetear base de datos, es eliminar toda la información que se encuentra en el sistema, está a su vez,restaura la base de datos a sus valores iniciales,en este proceso se debe ingresar  la super clave",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "como resetear base de datos, resetear base de datos, borrar base de datos,eliminar base de datos,base de datos"
    },
    {        
    id: 28,
    link: "SlFwHG8uUXg",
    alias: "salvar-datos-sincronizar-servidor",
    nombre: "salvar datos y sincronizar con el servidor",
    descripcion: "El proceso de salvar datos y sincronizar con el servidor, le permite guardar una copia de seguridad completa de todos los datos  de la ruta que tiene en el sistema, y a su vez este va directamente a la nube",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "salvar datos y sincronizar con el servidor, sincronizar con el servidor,salvar datos y sincronizar,sincronizar,salvar datos,servidor,datos,como salvar datos y sincronizar con el servidor"
    },
    {        
    id: 29,
    link: "Vg27f5p4xQ8",
    alias: "sincronizar-caja-liquidada",
    nombre: "sincronizar caja liquidada",
    descripcion: "El proceso de sincronizar caja liquidada, es descargar toda la información del recaudo del día y subirla a la nube, este a su vez  realiza un cierre de caja",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo sincronizar caja liquidada,sincronizar caja,caja liquidada,caja base,sincronizar caja liquidada,caja"
    },
    {        
    id: 30,
    link: "QxFRxJOmhIM",
    alias: "sincronizar-servidor-inicio-sesión",
    nombre: "sincronizar con el servidor desde el inicio de sesión",
    descripcion: "El proceso de sincronizar con el servidor desde el inicio de sesión, es guardar toda la información en la nube de forma segura",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo sincronizar con el servidor desde el inicio de sesión,como sincronizar con el servidor desde el inicio de sesión,sincronizar desde el inicio de sesión,sincronización desde el inicio de sesión,sincronizar desde el inicio de sesión,sincronización desde el inicio de sesión"
    },
    {        
    id: 31,
    link: "NnRrLe6TU1Q",
    alias: "ver-créditos-inactivos",
    nombre: "ver créditos inactivos",
    descripcion: "Esta opción, le permite ver todos los créditos cancelados que se encuentran registrados en el sistema, hasta la presente fecha presente fecha",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo ver los créditos inactivos,ver créditos inactivos, ver créditos,ver créditos cancelados,ver créditos inactivos,ver créditos cancelados,ver créditos"
    },
    {        
    id: 32,
    link: "UG66hyDc_bo",
    alias: "ver-detalles-crédito",
    nombre: "ver detalles de un crédito",
    descripcion: "El proceso de ver los detalles de un crédito,es mirar toda la información relacionada con la financiación del crédito",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo ver los detalles de un crédito,ver detalles de un crédito,como ver detalles de un crédito,mirar los detalles de un crédito,crédito,ver detalles,ver detalles de un crédito,ver financiación de  un crédito"
    },
    {        
    id: 33,
    link: "-sLliQfSJTA",
    alias: "ver-idapp",
    nombre: "ver idapp",
    descripcion: "El proceso de ver idapp le permite tener conocimiento del Id único de su aplicación",
    categoria: "liquida-pro",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_pro.jpg",
    keywords: "cómo ver el idapp,ver idapp,mirar idapp,observar idapp,ver el idapp, idapp"
    },
    {
    id: 34,
    link: "AvX4x9ocRTg",
    alias: "agregar-cliente-más crédito",
    nombre: "agregar cliente y asignarle crédito",
    descripcion: "El proceso de agregar cliente más crédito, es ingresar desde cero una venta, este procedimiento también lo puede realizar el dueño de la ruta, una vez esté creado el crédito deben salvar datos desde la app del cobrador para guardar los cambios",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "agregar caliente, nueva venta, agregar cliente más crédito, crédito nuevo, nuevo crédito, agregar cliente más crédito, ingresar un nuevo crédito"
    },
    {
    id: 35,
    link: "xtDWd7L5bqc",
    alias: "agregar-crédito-cliente-existente",
    nombre: "agregar crédito a un cliente existente",
    descripcion: "El proceso de agregar crédito a un cliente existente es, renovar una venta, en este proceso solo debe ingresar  los datos del crédito, ingrese la super clave para confirmar el crédito y salvar datos desde la app del cobrador para guardar los cambios y enrutar el crédito",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "agregar crédito a un cliente existente, agregar nueva venta a cliente existente, realizar credito a un cliente existente, ingresar crédito a un cliente existente, nueva venta a un cliente existente, realizar crédito a un cliente existente"
    },
    {
    id: 36,
    link: "5ZiJdvd7cYg",
    alias: "agregar-ruta-app-administrador",
    nombre: "agregar ruta en la app del administrador",
    descripcion: "El proceso de agregar ruta en la app del administrador es, ingresar las credenciales de cada una de las rutas que le manejan los cobradores, llevando así un mejor control sobre sus cuentas en liquida app",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "agregar ruta en la app de administrador, cómo agregar una ruta en la app del administrador, agregar ruta,ingresar una ruta en la app del administrador"
    },
    {
    id: 37,
    link: "rV27kseEAd4",
    alias: "borrar-modificar créditos",
    nombre: "barra,modificar créditos",
    descripcion: "El proceso de borrar, modificar un crédito, le permite realizar el cambio del saldo o eliminar el crédito del sistema si este es el caso, para este procedimiento debe ingresar la super clave y salvar datos en la app del cobrador para guardar los cambios",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "borrar un crédito, borrar, modificar créditos, como borrar un crédito, borrar un crédito, como borrar un crédito, eliminar un crédito, como eliminar un crédito, eliminar credito"
    },
    {
    id: 38,
    link: "7e468F20jV0",
    alias: "cambiar-datos-acceso de la ruta",
    nombre: "cambiar los datos de acceso de la ruta",
    descripcion: "El proceso de cambiar datos de acceso de la ruta , le permite modificar el usuario y la contraseña a la app del cobrador,  en este procedimiento debe ingresar la super clave y salvar datos desde liquida app",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cambiar datos de acceso, como cambiar datos de acceso, modificar datos de acceso, como modificar los datos de acceso de la app del cobrador, cambiar datos de acceso de la app del cobrador, modificar datos de acceso, como cambiar los datos de acceso de una ruta"
    },
    {
    id: 39,
    link: "Q1Rtk3gfkng",
    alias: "cambiar-super-clave",
    nombre: "cambiar super clave",
    descripcion: "El proceso de cambiar la super clave, le permite al administrador de la ruta colocar una de su preferencia la cual puede recordar con facilidad, una vez realice el cambio  debe salvar datos en la app del cobrador para guardar los cambios",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo cambiar la super clave, cambiar super clave, modificar super clave, como modificar la super clave, como modificar super clave"
    },
    {
    id: 40,
    link: "tMufAZzfM9s",
    alias: "cartera-actual",
    nombre: "cartera actual",
    descripcion: "El proceso de la cartera actual, es un resumen detallado sobre el portafolio activo de la ruta, igual que todos los datos recientes de la cartera por cobrar del día",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver la cartera actual, cartera actual, resumen de la cartera actual, datos de la cartera actual, ver información de la cartera actual"
    },
    {
    id: 41,
    link: "tfdxhawP5-c",
    alias: "clientes-inactivos por calificación",
    nombre: "clientes inactivos por calificación",
    descripcion: "El proceso de ver los clientes inactivos por calificación, es un listado completo y detallado de todos los créditos que fueron cancelados en el sistema y a su vez la calificación que arroja el sistema respecto a la puntualidad del pago",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver los clientes inactivos por calificación, clientes inactivos, clientes por calificación, ver clientes inactivos por calificación, clientes por calificación"
    },
    {
    id: 42,
    link: "SguTaPDWsA4",
    alias: "borrar-abonos-pagos",
    nombre: "como borrar abonos,pagos",
    descripcion: "Esta opción le permite eliminar definitivamente del sistema el abono de la fecha que necesite, para realizar este proceso debe ingresar la super clave y salvar datos desde la app del cobrador para guardar los cambios",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo borrar abonos y pagos, borrar abonos y pagos, como borrar un abono, como borrar un pago, como eliminar un pago, borrar abono, eliminar abono, como eliminar abonos y pagos, borrar abono, borrar pago,como eliminar un paga, como eliminar un abono"
    },
    {
    id: 43,
    link: "PBmnQlts8TQ",
    alias: "eliminar-gastos-entradas-ingresos",
    nombre: "como eliminar gastos,entregas, ingresos",
    descripcion: "Esta opción le permite eliminar definitivamente del sistema uno de los  siguientes pasos, los gastos, las entregas o los ingresos, para este procedimiento debe ingresar la fecha del gasto, entrega o inversión que necesita eliminar,  ingresar la super clave y salvar datos desde la app del cobrador",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo eliminar gastos, entregas e inversiones, como eliminar gasto, como eliminar una entrega, como eliminar un gasto, como eliminar un ingreso, eliminar entrega, como eliminar una inversión, eliminar gastó, eliminar inversion, eliminar inversion"
    },
    {
    id: 44,
    link: "c1Aa07gGkC8",
    alias: "entregas-salidas por fecha",
    nombre: "entregas y salidas por fecha",
    descripcion: "el proceso de entregas y salidas por fecha, le brinda un reporte detallado de todos los aportes y las salidas de dinero que se ingresaron en el sistema y se le entregaron a socios y administradores de la ruta, para este procedimiento debe ingresar la fecha en la cual desea obtener la información",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver entregas y salidas por fecha, entregas y salidas, entregas y salidas por fecha, entregas por fecha, salidas por fecha, ver entregas por fecha, ver salidas por fecha, entregas,salidas"
    },
    {
    id: 45,
    link: "EEtJhIm82lQ",
    alias: "liquidar-ruta",
    nombre: "liquidar ruta",
    descripcion: "el proceso de liquidar ruta es, guardar toda la información diaria ingresada en el sistema, este procedimiento se puede realizar desde la app del cobrador o del administrador, es decisión del encargado de la ruta si cierran caja, semanal,quincenal o mensual, este reporte también lo puede ver por fechas",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo liquidar ruta, liquidar ruta"
    },
    {
    id: 46,
    link: "G-E4jLV_eIo",
    alias: "restringir-acciones de ruta",
    nombre: "restringir acciones de ruta",
    descripcion: "el proceso de restringir acciones de ruta es, colocar límites o no tener ningún tipo de restricción en el manejo y las funciones de la ruta del cobrador o encargado, para aplicar cualquier tipo de cambio debe ingresar la super clave y salvar datos desde la app del cobrador",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "restringir acciones de ruta,como restringir acciones de ruta,restringir manejo en la ruta,como disminuir acciones en la ruta,disminuir manejo en la ruta"
    },
    {
    id: 47,
    link: "hK2tpvlmCg8",
    alias: "ver-crecimiento de cartera",
    nombre: "ver crecimiento de cartera",
    descripcion: "el proceso de ver crecimiento de cartera, le permite tener un reporte completo del aumento del portafolio de la ruta, bien sea positivo o negativo",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver el crecimiento de la cartera,ver crecimiento de cartera,crecimiento de cartera,ver aumento de la cartera,aumento de la cartera"
    },
    {
    id: 48,
    link: "Pu9c1IGfFgw",
    alias: "ver-créditos activos-todos los clientes",
    nombre: "ver créditos activos,todos los clientes",
    descripcion: "el proceso de ver créditos activos, todos los clientes, le permite ver un registro completo de todos los créditos ingresados en el sistema hasta la fecha, este procedimiento le muestra un informe detallado de todos los abonos del crédito, el estado actual y el capital activo que tiene hasta el momento",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver los créditos activos todos los clientes, ver créditos activos todos los clientes,créditos activos todos los clientes,como ver los créditos activos, como ver los créditos activos todos los clientes, como ver los créditos activos"
    },
    {
    id: 49,
    link: "j3osgFmUQjY",
    alias: "ver-créditos-según estado",
    nombre: "ver créditos según estado",
    descripcion: "el proceso de ver créditos según estado,le permite revisar la información de todos y cada uno de los clientes a los cuales le realizaron en el crédito una refinanciación, multa, o descuento",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver los créditos según estado, ver créditos según estado, créditos según estado, como ver los créditos según estado, ver estado de los créditos, créditos según estado, ver estado de los créditos"
    },
    {
    id: 50,
    link: "gm75pTsJ1zA",
    alias: "ver-créditos-vencidos",
    nombre: "ver créditos vencidos",
    descripcion: "el proceso de ver créditos vencidos, es tener un registro en el sistema de todos los clientes que aún tienen un saldo pendiente en el crédito y tienen vencido el plazo a pagar",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "ver créditos vencidos, como ver los créditos vencidos, ver créditos vencidos, como ver los créditos vencidos, créditos vencidos, crédito con plazo vencido, créditos vencidos, créditos con el plazo vencido"
    },
    {
    id: 51,
    link: "GcslRlAUOKw",
    alias: "ver-gastos por fecha",
    nombre: "ver gastos por fecha",
    descripcion: "La opción de ver gastos por fecha, le permite tener un listado detallado de todos los desembolsos registrados en la ruta de la fecha seleccionada",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "gastos por fecha, como ver gastos por fecha, mirar gastos por fecha, listado de gastos por fecha, ver gastos por fecha, ver desembolso por fecha"
    },
    {
    id: 52,
    link: "d1SIvOkTjq8",
    alias: "ver-inversiones por fecha",
    nombre: "ver inversiones por fecha",
    descripcion: "el procedimiento de ver inversiones por fecha le muestra una información detallada de todas las entradas que ingresaron en la fecha que necesite",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "ver inversiones por fecha, inversiones por fecha, como ver todas las inversiones por fecha, ver las inversiones por fecha, ver inversiones, inversión por fecha"
    },
    {
    id: 53,
    link: "zWZUHZbHBUk",
    alias: "ver-listado-recaudado del día",
    nombre: "ver listado de recaudado del día",
    descripcion: "el proceso de ver listado de recaudado del día, es un informe completo con la cantidad de créditos por cobrar y el valor total para cobrar del presente dia de todos los créditos activos y vencidos",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver el listado de recaudado del día, ver lista de recaudo, como ver la lista de recaudado del día, ver listado de recaudo, ver lista de recaudo"
    },
    {
    id: 54,
    link: "rWVEP8W1o1Q",
    alias: "ver-recaudado por fecha",
    nombre: "ver recaudado por fecha",
    descripcion: "el proceso de ver recaudado por fechas es un resumen de los abonos que se recibieron y se registraron en el sistema de todos los créditos en la fecha seleccionada",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "ver recaudado por fecha, como ver recaudado por fecha, recaudado por fecha, listado del recaudado por fecha, como ver el recaudado por fecha, ver recaudo por fecha, ver recaudo"
    },
    {
    id: 55,
    link: "hBJR0rsfbj0",
    alias: "ver-liquidaciones",
    nombre: "ver liquidaciones",
    descripcion: "Esta opción le permite ver un resumen de todos los cierres de caja que se registraron el el sistema hasta la fecha con sus respectivas fechas, los detalles del día del cierre y la opción de volver abrir las caja si es necesario el caso",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "ver recaudado por fecha, como ver recaudado por fecha, recaudado por fecha, listado del recaudado por fecha, como ver el recaudado por fecha, ver recaudo por fecha, ver recaudo"
    
    },
    {
    id: 56,
    link: "SP1nUrWd0yc",
    alias: "ver-resumen por fecha",
    nombre: "ver resumen por fecha",
    descripcion: "el proceso de ver resumen por fecha, es toda la recopilación que se ingresa en el sistema de los créditos, las inversiones, los gastos, las entregas y los recaudos de la fecha que selecciona",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver el resumen por fecha, ver  resumen por fecha, mirar resumen por fecha, resumen por fecha"
    },
    {
    id: 57,
    link: "k7iYmHilMa8",
    alias: "ver-créditos por fecha",
    nombre: "ver créditos por fecha",
    descripcion: "La opción de ver créditos por fecha, le permite tener una información detallada de la cantidad de créditos  y el valor total  que se registraron en el sistema en la fecha seleccionada en la fecha seleccionada",
    categoria: "liquida-master",
    fecha_pub: "2019-01-25",
    cant_reproduc: 0,
    img: "assets/img/img_master.jpg",
    keywords: "cómo ver los créditos por fecha, ver créditos por fecha, mirar créditos por fecha por fecha, creditos por fecha, como ver créditos por fecha, ver créditos por fecha, mirar créditos por fecha, créditos por fecha"
    }];
    