
export let vids: any[] = [
{
id: 1,
link: "zg9Em90A9nw",
alias: "crear-cliente-1",
nombre: "crear un cliente nuevo, método 1",
descripcion: "El proceso de crear un cliente nuevo metodo 1, es realizar una venta desde cero, ingresando correctamente los datos del cliente, como del crédito",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "nuevo 1,crear cliente 1,registrar 1,cliente nuevo 1,nueva venta 1,registrar,cliente nuevo,registrar cliente 1, registro 1"

},
{      
id: 2,
link: "KAKpliwnPk4",
alias: "crear-cliente-2",
nombre: "crear un cliente nuevo, método 2",
descripcion: "El proceso de crear un cliente nuevo método 2, es realizar una venta desde cero, ingresando los datos del cliente como del crédito de forma sencilla",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "nuevo 2, crear cliente 2, registrar 2, cliente nuevo 2, nueva venta 2, registrar, cliente nuevo, registrar cliente 2, registro 2"
},
{        
id: 3,
link: "I3RtGpLB1HQ",
alias: "ingresar-abono-crédito-método 1",
nombre: "ingresar abono a un crédito, método 1",
descripcion: "El proceso de ingresar abono a un crédito método 1, es recaudar y registrar en el sistema el abono del cliente los días y la fecha seleccionada",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "nuevo abono, ingresar abono, abonar crédito 1, abonar 1, ingresar abono 1, ingresar 1, credito 1, abonar credito, como ingresar un abono a un crédito método 1, crédito, como ingresar abono a un credito metodo 1"
},
{        
id: 4,
link: "BH26mDfeSz0",
alias: "ingresar-abono-crédito-método 2-abonar-súper-usuario",
nombre: "ingresar abono a un crédito, método 2 más abonar como súper usuario",
descripcion: "El proceso de ingresar abono a un crédito método 2, más abonar como súper usuario es registrar el pago del abono en el sistema, si va abonar como super usuario debe ingresar la súper clave, en este proceso debe cambiar la fecha del abono por el día anterior ya que el sistema no permite ingresar dos veces el abono el mismo día",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "ingresar abono, crédito 2, método 2, abonar súper usuario, ingresar 2, abonar 2, crédito 2, abonar, ingresar abono, credito 2"
},
{        
id: 5,
link: "NiNNp0xh95s",
alias: "aplazar-crédito-lista de recaudo-método 1",
nombre: "aplazar un crédito desde la lista de recaudo método 1",
descripcion: "El proceso de aplazar un crédito desde la lista de recaudo es posponer el crédito solo por un tiempo de mes y medio, este proceso lo puede realizar ingresando directamente al crédito desde la ruta de recaudo",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "aplazar 1, aplazar crédito 1, lista de recaudo 1, recaudo 1, aplazar crédito método 1, como aplazar crédito, aplazar un crédito, aplazar credito 1, como aplazar credito, credito 1"
},
{        
id: 6,
link: "RhnNXGM80Ks",
alias: "aplazar-crédito-lista de recaudo-método 2",
nombre: "aplazar un crédito desde la lista de recaudo método 2",
descripcion: "El proceso de aplazar un crédito desde la lista de recaudo método 2,es postergar el crédito solo por un tiempo de un mes o un mes y medio, ese es el plazo que permite registrar el sistema",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "aplazar crédito 2, aplazar 2, método 2, lista de recaudo 2, crédito 2, aplazar crédito, aplazar un crédito, como aplazar un crédito,credito 2, aplazar credito 2, plazar credito, como aplazar un credito, aplazar un credito desde la ruta de recaudo 2,como aplazar un credito desde la ruta de recaudo 2 "
},
{        
id: 7,
link: "3N9ImmwLQ-4",
alias: "agregar-crédito-lista de recaudo-día",
nombre: "agregar un crédito a la lista de recaudo del día",
descripcion: "El proceso de agregar un crédito a la lista de recaudo, es añadir el cliente a la ruta de cobro sea diaria, semana, quincenal o mensual",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "agregar crédito, recaudo del día, agregar crédito a lista, añadir crédito a lista, añadir crédito a la lista de recaudo, agregar un credito a la lista de recaudo del dia, agregar credito, añadir credito a la lista"
},
{        
id: 8,
link: "Q0To7VN300M",
alias: "agregar-quitar-gasto en el balance",
nombre: "agregar,quitar gasto en el balance",
descripcion: "El proceso de agrega, quitar gasto en el balance, es registrar un control diario en el sistema de los gastos y las inversiones que se presente",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "agregar gasto, quitar un gasto, registrar un gasto, ingresar una inversión, eliminar un gasto,eliminar una inversión, registrar un gasto, registrar una inversión, agregar una salida, registrar una entrada, registrar una inversion"
},
{        
id: 9,
link: "VVbAnGVpTD0",
alias: "cambiar-cliente- posición en la ruta",
nombre: "cambiar un cliente de posición en la ruta",
descripcion: "El proceso de cambiar un cliente de posición en la ruta, es ubicar el crédito en el lugar de su preferencia, puede ser en los primeros lugares, en la mitad o en el último lugar ",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "cambiar cliente, cambiar posición, nueva posición, cambiar cliente de lugar,cambiar cliente de posición en la ruta,elegir nueva posición, posicionar cliente,cambiar cliente de pósicion"
},
{        
id: 10,
link: "a-iWLBh6CqA",
alias: "iniciar-sesión",
nombre: "como iniciar sesión",
descripcion: "El proceso de iniciar sesión, es ingresar correctamente los datos de acceso a la cuenta",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como inicio sesión, iniciar sesion, inicio, inicio de sesion, como iniciar sesion, iniciar sesión, inicio de sesión"
},
{        
id: 11,
link: "By9aewWNlZA",
alias: "borrar-abono",
nombre: "como borrar un abono",
descripcion: "El proceso de como borrar un abono, es eliminar un mal procedimiento realizado en el sistema, en este proceso debe ingresar la super clave para eliminar el abono en el crédito",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como borrar abono, borrar un abono, eliminar un abono, quitar un abono, quitar un abono del credito, quitar un abono"
},
{        
id: 12,
link: "d_lAqj7nKKA",
alias: "cambiar-idapp",
nombre: "como cambiar el idapp",
descripcion: "El proceso de cambiar el idapp, es modificar el ID único de la aplicación la cual está manejando, para realizar este procedimiento debe ingresar el nuevo idapp y la súper clave en los campos correspondientes",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "cambio de idapp, cambiar idapp, como cambiar el idapp, modificar el idapp, modificar idapp, idapp"
},
{        
id: 13,
link: "Tf8aVhbEjpE",
alias: "eliminar-crédito",
nombre: "como eliminar un crédito",
descripcion: "El proceso de como eliminar un crédito, es quitar del sistema el crédito que no se necesite, pero los datos del cliente continúan en el sistema, esta acción se realiza ingresando la súper clave",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como eliminar un crédito, borrar crédito, eliminar crédito, quitar crédito, eliminar del sistema un crédito, borrar credito"
},
{        
id: 14,
link: "3etzS6J1tCQ",
alias: "función-balance",
nombre: "cómo funciona el balance",
descripcion: "Este procedimiento le permite tener un registro detallado de todos los datos que se ingresan en el sistema, y la información completa de cada una de las fechas que necesite",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como funciona el balance, función del balance, información del balance, descripción del balance, balance"
},
{        
id: 15,
link: "Ph2NqlXJWhM",
alias: "recuperar-cuenta",
nombre: "cómo recuperar cuenta",
descripcion: "Este proceso le permite rescatar toda la información de la cuenta, la cual esta activa en la nube, para este proceso solo debe ingresar el idapp y el serial de la cuenta a recuperar",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como recuperar cuenta, recuperar cuenta, recuperación de cuenta, cuenta, recuperar, cuenta a recuperar, proceso de recuperacion de cuenta"
},
{        
id: 16,
link: "DlaFp7NcfLU",
alias: "sincronizar-caja-desde el balance",
nombre: "cómo sincronizar la caja desde el balance",
descripcion: "El proceso de sincronizar la caja desde el balance, le permite mantener actualizada la informacion de su cuenta en la nube",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como sincronizar caja, actualizar caja, sincronizar la caja desde el balace, actualizar caja desde el balance, sincronizar caja, caja, sincronizar, balance"
},
{        
id: 17,
link: "hZITVj8-o88",
alias: "copia-local",
nombre: "copia local",
descripcion: "El proceso de copia local, le permite recuperar los datos que estan almacemados de la cuenta en la nube, este procedimeinto lo puede realizar ingresando el idapp y el seria de la cuenta a recupar",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "copia local, copia, recuperar copia, recuperación de datos, recuperar copia local desde la nube, recuperar datos, copia, local"
},
{        
id: 18,
link: "Qnm8zE2N-so",
alias: "descargar-caja-base",
nombre: "descargar caja base",
descripcion: "El proceso de descargar caja base, le permite sincronizar la caja base desde el servidor",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como descargar caja base, caja base, descargar caja, descargar caja base, como puedo descargar caja base, caja, caja base, descargar"
},
{        
id: 19,
link: "R1U9UbzUmvg",
alias: "enrutar-crédito",
nombre: "enrutar un crédito",
descripcion: "El proceso de enrutar un crédito le permite añadir y posicionar el cliente al principio, en la mitad o al final en la lista general de recaudo",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como enrutar un crédito, enrutar crédito, enrutar, enrutar un crédito"
},
{        
id: 20,
link: "-RC67AorGic",
alias: "hacer-descuento-crédito",
nombre: "hacer un descuento a un crédito",
descripcion: "El proceso de hacer un descuento a un crédito, es un beneficio que puede aplicar la persona encargada de la ruta en algunos clientes, bien sea por su pago constante o por realizar la cancelación total del crédito ",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como hacer un descuento a un crédito, descuento a un crédito, realizar descuento a un crédito, descontarle a un crédito, rebaja a un crédito, hacer una rebaja a un credito"
},
{        
id: 21,
link: "q_Vgbvlw2Qc",
alias: "hacer-multa-crédito",
nombre: "hacer una multa a un crédito",
descripcion: "El proceso de hacer una multa a un crédito, es penalizar el crédito realizando un aumento bien sea en los intereses, este proceso lo aplica el encargado de la ruta en algunos clientes, bien sea por demora en la cancelación del crédito",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como hacer una multa a un crédito, multar a un crédito, realizar una multa a un crédito, multar a un crédito, multa a un crédito, multar un crédito"
},
{        
id: 22,
link: "XBYzlPWCnwM",
alias: "limpiar-ruta",
nombre: "limpiar ruta",
descripcion: "El proceso de limpiar ruta, es quitar todas las posiciones del sistema que no se esta utilizando, pero sin borrar los datos antiguos, este proceso es para mejorar el rendimiento del sistema",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como limpiar ruta, limpiar ruta, limpiar, quitar posiciones del sistema"
},
{        
id: 23,
link: "DAHb7oFbapY",
alias: "modificar-datos-acceso",
nombre: "modificar datos de acceso",
descripcion: "El proceso de modificar datos de acceso le permite personalizar los datos de usuario y contraseña, tenga en cuenta que el sistema no permite ingresar caracteres especiales, tildes o espacios en los campos de usuario y contraseña",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como modificar los datos de acceso, modificar datos de acceso, datos de acceso, cambiar datos de acceso, modificar datos"
},
{        
id: 24,
link: "HxPCSkr_LjI",
alias: "modificar-crédito",
nombre: "modificar un crédito",
descripcion: "El proceso de modificar un crédito, es corregir los datos ingresados en el sistema de un crédito, este proceso se realiza ingresando la super clave",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como modificar los datos de un crédito, modificar crédito, cambiar los datos de un crédito, modificar un crédito"
},
{        
id: 25,
link: "y1u1k-MGNVI",
alias: "realizar-mantenimiento-optimización",
nombre: "realizar mantenimiento de optimización",
descripcion: "El proceso de realizar mantenimiento y optimización,le permite limpiar los datos antiguos de la aplicación,tambien le ayuda acelera el funcionamiento de la aplicación",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "realizar mantenimiento y optimización, mantenimiento y optimización,mantenimiento y optimización de una ruta, como realizar mantenimiento de optimización, como hacer mantenimiento y optimizacion de una ruta"
},
{        
id: 26,
link: "Rtpw-Oee0YQ",
alias: "renovar-crédito-cancelado",
nombre: "renovar un crédito cancelado",
descripcion: "El proceso de renovar un crédito cancelado, es reanudar un crédito inactivo, en este procedimiento solo tiene que ingresar los datos del crédito ya que la información del cliente queda guardada en el sistema",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "renovar crédito cancelado,como renovar un crédito cancelado,renovar crédito,reanudar un crédito cancelado,reanudar un crédito,renovar credito cancelado,como renovar un credito cancelado,renovar credito"
},
{        
id: 27,
link: "LZxItOZhql0",
alias: "resetear-base-datos",
nombre: "resetear base de datos",
descripcion: "El proceso de resetear base de datos, es eliminar toda la informacion que se encuentra en la base de datos del sistema, esta a su vez,restaura la base de datos a sus valores iniciales,este proceso se realiza ingresando la super clave",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como resetear base de datos, resetear base de datos, borrar base de datos,eliminar base de datos,base de datos"
},
{        
id: 28,
link: "uECJrcT8dkE",
alias: "salvar-datos-sincronizar-servidor",
nombre: "salvar datos y sincronizar con el servidor",
descripcion: "El proceso de salvar datos y sincronizar con el servidor, le permite guardar una copia de segurida completa de todos los datos que tiene en el sistema, este va directamente a la nube",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "salvar datos y sincronizar con el servidor, sincronizar con el servidor,salvar datos y sincronizar,sincronizar,salvar datos,servidor,datos,como salvar datos y sincronizar con el servidor"
},
{        
id: 29,
link: "oW8FCSK5sPY",
alias: "sincronizar-caja-liquidada",
nombre: "sincronizar caja liquidada",
descripcion: "El proceso de sincronizar caja liquidada, es descargar toda la información del recaudo del día, este a su vez  realiza un cierre de caja",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como sincronizar caja liquidada,sincronizar caja,caja liquidada,caja base,sincronizar caja liquidada,caja"
},
{        
id: 30,
link: "VjvASDyZZpk",
alias: "sincronizar-servidor-inicio-sesión",
nombre: "sincronizar con el servidor desde el inicio de sesión",
descripcion: "El proceso de sincronizar con el servidor desde el inicio de sesión, es guardar toda la información en la nube de forma segura",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como sincronizar con el servidor desde el inicio de sesión,como sincronizar con el servidor desde el inicio de sesion,sincronizar desde el inicio de sesion,sincronización desde el inicio de sesión,sincronizar desde el inicio de sesión,sincronización desde el inicio de sesion"
},
{        
id: 31,
link: "7zicdJG2oVA",
alias: "ver-créditos-inactivos",
nombre: "ver créditos inactivos",
descripcion: "El proceso de ver los créditos inactivos,le permite ver en el sistema todos los créditos cancelados hasta la presente fecha",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como ver los créditos inactivos,ver créditos inactivos, ver creditos,ver creditos cancelados,ver creditos inactivos,ver créditos cancelados,ver créditos"
},
{        
id: 32,
link: "RuOgZA--aqU",
alias: "ver-detalles-crédito",
nombre: "ver detalles de un crédito",
descripcion: "El proceso de ver los detalles de un crédito,es mirar toda la información relacionada con la financiación del crédito",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como ver los detalles de un crédito,ver detalles de un credito,como ver detalles de un credito,mirar los detalles de un crédito,credito,ver detalles,ver detalles de un crédito,ver financiacion de u credito"
},
{        
id: 33,
link: "SDbaNf8nbQg",
alias: "ver-idapp",
nombre: "ver idapp",
descripcion: "El proceso de ver idapp le permite tener conocimiento del id unico de su aplicación",
categoria: "liquida-pro",
fecha_pub: "2018-11-09",
cant_reproduc: 0,
img: "assets/img/img_pro.jpg",
keywords: "como ver el idapp,ver idapp,mirar idapp,observar idapp,ver el idapp, idapp"
},
{
id: 34,
link: "6K-Pm7FpUAE",
alias: "agregar-cliente-con-credito",
nombre: "agregar cliente y asignarle crédito",
descripcion: "El proceso de agregar cliente mas crédito, es ingresar desde cero una venta, este procedimiento lo realiza el encargado de la ruta y se salvan datos desde la app del cobrador para guardar los cambios",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "agregar cliente, nueva venta, agregar cliente mas crédito, credito nuevo, nuevo crédito, agregar cliente mas credito, ingresar un nuevo credito"
},
{
id: 35,
link: "U3C-Jqdntg8",
alias: "agregar-credito-cliente-existente",
nombre: "agregar crédito a un cliente existente",
descripcion: "El proceso de agregar crédito a un cliente existente es, renovar una venta, en este proceso ingresa los datos del crédito, luego ingresa la super clave para confirmar el crédito y salvar datos desde la app del cobrador para luego enrutar el crédito",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "agregar credito a un cliente existente, agregar nueva venta a cliente existente, realizar credito a un cliente existente, ingresar credito a un cliente existente, nueva venta a un cliente existente, realizar crédito a un cliente existente"
},
{
id: 36,
link: "5vFeOw_nNIE",
alias: "agregar-ruta-app-administrador",
nombre: "agregar ruta en la app del administrador",
descripcion: "El proceso de agregar ruta en la app del administrador es, ingresar las credenciales de la ruta,este proceso le permite llevar un control sobre sus cuentas en liquida app",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "agregar ruta en la app de administrador, como agregar una ruta en la app del administrador, agragar ruta,ingresar una ruta en la app del administrador"
},
{
id: 37,
link: "iJaQe1CSTM4",
alias: "borra-modificar créditos",
nombre: "barra,modificar créditos",
descripcion: "El proceso de borrar, modificar un crédito, le permite cambiar el saldo del crédito o eliminar el crédito del sistema si es el caso, para este procedimientos debe ingresar la super clave y salvar datos en la app del cobrador para guardar los cambios",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "borrar un crédito, borrar, modificar creditos, como borrar un crédito, borrar un credito, como borrar un credito, eliminar un crédito, como eliminar un credito, eliminar credito"
},
{
id: 38,
link: "3DH1KHqmz3M",
alias: "cambiar-datos-acceso de la ruta",
nombre: "cambiar datos de acceso de la ruta",
descripcion: "El proceso de cambiar datos de acceso de la ruta es, modificar las referencias de acceso de la app del cobrador, en este procedimiento debe ingresar la super clave y salvar datos desde la liquida app",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "cambiar datos de acceso, como cambiar datos de acceso, modificar datos de acceso, como modificar los datos de acceso de la app del cobrador, cambiar datos de acceso de la app del cobrador, modificar datos de acceso, como cambiar los datos de acceso de una ruta"
},
{
id: 39,
link: "W2-7KE9yAjc",
alias: "cambiar-super-clave",
nombre: "cambiar super clave",
descripcion: "El proceso de cambiar la super clave, le permite al administrador de la ruta colocar una de su prefernecia la cual puede recordar con facilidad, una vez realice el cambio de super claven deben salvar datos de la app del cobrador para guardar los cambios",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como cambiar la super clave, cambiar super clave, modificar super clave, como modificar la super clave, como modificar super clave"
},
{
id: 40,
link: "AZeCH9FDitQ",
alias: "cartera-actual",
nombre: "cartera actual",
descripcion: "El proceso de la cartera actual, es un resumen detallado sobre el portafolio activo y todos los datos recientes de la cartera por cobrar del día",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver la cartera actual, cartera actual, resumen de la cartera actual, datos de la cartera actual, ver informacion de la cartera actual"
},
{
id: 41,
link: "GKOfGZUos1k",
alias: "clientes-inactivos por calificación",
nombre: "clientes inactivos por calificación",
descripcion: "El proceso de ver los clientes inactivos por calificación, es un listado completo y detallado de todos los créditos respecto a la puntualidad de pago que tubo con el crédito",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver los clientes inactivos por calificación, clientes inactivos, clientes por calificacion, ver clientes inactivos por calificacion, clientes por calificación"
},
{
id: 42,
link: " LuLkoEgFpQ0",
alias: "borrar-abonos-pagos",
nombre: "como borrar abonos,pagos",
descripcion: "la opción de borrar los abonos y pagos, es liquidar del sistema la entrega de la fecha que necesite, en este proceso debe ingresar la super clave y salvar datos desde la app del cobrador para guardar los cambios",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como borrar abonos y pagos, borrar abonos y pagos, como borrar un abono, como borrar un pago, como eliminar un pago, borrar abono, eliminar abono, como eliminar abonos y pagos, borrar abono, borrar pago,como eliminar un paga, como eliminar un abono"
},
{
id: 43,
link: "yFGWET-i02w",
alias: "eliminar-gastos-entradas-inversión",
nombre: "como eliminar gastos,entregas he inversiones",
descripcion: "el proceso de eliminar los gastos, las entregas y las inversiones es, borrar definitivamente del sistemas la opción que necesite, para este procedimiento debe ingresar la fecha del gasto, entrega o inversión que necesita eliminar, debe ingresar la super clave y salvar datos desde la app del cobrador",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como eliminar gastos, entregas he inversiones, como eliminar gasto, como eliminar una entrega, como eliminar un gasto, como eliminar una inversión, eliminar entrega, como eliminar una inversion, eliminar gasto, eliminar inverssión, eliminar inversion"
},
{
id: 44,
link: "NMQc6fmbknw",
alias: "entregas-salidas por fecha",
nombre: "entregas y salidas por fecha",
descripcion: "el proceso de entregas y salidas por fecha, le brinda un reporte detallado de todos los aportes y las salidas entregadas a socion o aministradores de la ruta, en este procedimiento debe ingresar la fecha en la cual desea obtener la información",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver entregas y salidas por fecha, entregas y salidas, entregas y salidas por fecha, entregas por fecha, salidas por fecha, ver entregas por fecha, ver salidas por fecha, entrergas,salidas"
},
{
id: 45,
link: "ctuiaidAKrE",
alias: "liquidar-ruta",
nombre: "liquidar ruta",
descripcion: "el proceso de liquidar ruta es, guargar toda la información diaria ingresada en el sistema, este procedimiento se puede realizar desde la app del cobrador o del administrador, es decisión del encargado de la ruta si cierran caja, semanal,quincenal o mensual, este reporte lo puede ver por fechas",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como liquidar ruta, liquidar ruta"
},
{
id: 46,
link: "7pvbfnFvdww",
alias: "restringir-acciones de ruta",
nombre: "restringir acciones de ruta",
descripcion: "el proceso de restringir acciones de ruta es, colocar limites en el manejo y las funciones de la ruta del cobradores o encargados, para aplicar cualquier tipo de cambio debe ingresar la super clave y salvar datos desde la app del cobrador",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "restringir acciones de ruta,como restringir acciones de ruta,restringir manejo en la ruta,como disminuir acciones en la ruta,disminuir manejo en la ruta"
},
{
id: 47,
link: "eNJwWLkoUC4",
alias: "ver-crecimiento de cartera",
nombre: "ver crecimiento de cartera",
descripcion: "el proceso de ver crecimiento de cartera, le permite mirar un reporte completo del aumento del portafolio de la ruta bien sea positivo o negativo",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver el crecimiento de la cartera,ver crecimiento de cartera,crecimiento de cartera,ver aumento de la cartera,aumento de la cartera"
},
{
id: 48,
link: "vrbKIEVQLJM",
alias: "ver-créditos activos-todos los clientes",
nombre: "ver créditos activos,todos los clientes",
descripcion: "el proceso de ver créditos activos, todos los clientes, le permite ver un registro completo de todos los créditos ingresados en el sistema hasta la fecha, este procedimiento le muestra un informe detallado del estado actual y el capital activo de todos los crédito",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver los créditos activos todos los clientes, ver creditos activos todos los clientes,créditos activos todos los clientes,como ver los creditos activos, como ver los creditos activos todos los clientes, como ver los créditos activos"
},
{
id: 49,
link: "l5wsp4BRXFM",
alias: "ver-créditos-según estado",
nombre: "ver créditos según estado",
descripcion: "el proceso de ver créditos según estado,le permite revisar la información de todos los clientes a los cuales le realizarón en el crédito una refinanciación, multa, o descuento",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver los créditos según estado, ver créditos según estado, créditos según estado, como ver los creditos segun estado, ver estado de los créditos, creditos segun estado, ver estado de los créditos"
},
{
id: 50,
link: "1kCTOzfWZYY",
alias: "ver-créditos-vencidos",
nombre: "ver créditos vencidos",
descripcion: "el proceso de ver créditos vencidos, es tener un registro en el sistema de todos los clientes que aun tienen un saldo pendiente en el crédito y tienen vencido el plazo a pagar",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "ver créditos vencidos, como ver los créditos vencidos, ver creditos vencidos, como ver los creditos vencidos, creditos vencidos, credito con plazo vencido, créditos vencidos, créditos con el plazo vencido"
},
{
id: 51,
link: "pfjvi2DZGnA",
alias: "ver-gastos por fecha",
nombre: "ver gastos por fecha",
descripcion: "el procedimiento de ver gastos por fecha le permite mirar un listado de todos los desembolsos de la ruta que se realizarón en la fecha que seleccione",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "gastos por fecha, como ver gastos por fecha, mirar gastos por fecha, listado de gastos por fecha, ver gastos por fecha, ver desembolso por fecha"
},
{
id: 52,
link: "d1SIvOkTjq8",
alias: "ver-inversiones por fecha",
nombre: "ver inversiones por fecha",
descripcion: "el procedimiento de ver inversiones por fecha le muestra una información detallada de todas las entradas que ingresarón en la fecha que necesite",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "ver inversiones por fecha, inversiones por fecha, como ver todas las inversiones por fecha, ver las inversiones por fecha, ver inversiones, inversion por fecha"
},
{
id: 53,
link: "3pMFAubGVQ0",
alias: "ver-listado-recaudado del día",
nombre: "ver listado de recaudado del día",
descripcion: "el proceso de ver listado de recaudado del día, es un informe completo de todos los créditos activos y vencidos por cobrar",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver el listado de recaudado del día, ver lista de recaudo, como ver la lista de recaudado del dia, ver listado de recaudo, ver lista de recaudo"
},
{
id: 54,
link: "T1tR4W8yleU",
alias: "ver-recaudado por fecha",
nombre: "ver recaudado por fecha",
descripcion: "el proceso de ver recaudado por fechas es un resumen de los abonos que se recibierón de todos los créditos en la fecha seleccionada",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "ver recaudado por fecha, como ver recaudado por fecha, recaudado por fecha, listado del recaudado por fecha, como ver el recuadado por fecha, ver recaudo por fecha, ver recaudo"
},
{
id: 55,
link: "e2S0tLit8iw",
alias: "ver-resumen por fecha",
nombre: "ver resumen por fecha",
descripcion: "el proceso de ver resumen por fecha, es toda la recopilación que se ingresa en el sistema de los créditos, las inversiones, los gastos, las entregas y los recaudos de la fecha que selecciona",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver el resumen por fecha, ver  resumen por fecha, mirar resumen por fecha, resumen por fecha"
},
{
id: 56,
link: "qUVghqo2BJE",
alias: "ver-créditos por fecha",
nombre: "ver créditos por fecha",
descripcion: "el proceso de ver créditos por fecha, le permite tener una información detallada de la cantidad de créditos que tiene y el valor total de la fecha que seleccione",
categoria: "liquida-master",
fecha_pub: "2018-11-20",
cant_reproduc: 0,
img: "assets/img/img_master.jpg",
keywords: "como ver los creditos por fecha, ver creditos por fecha, mirar creditos por fecha por fecha, creditos por fecha, como ver créditos por fecha, ver créditos por fecha, mirar créditos por fecha, créditos por fecha"
}];